#FROM - Image to start building on.
FROM ubuntu:14.04

#RUN - Runs a command in the container
RUN echo "Hello world" > /root/hello_world.txt

#CMD - Identifies the command that should be used by default when running the image as a container.
CMD ["cat", "/root/hello_world.txt"]